import Navbar from "@/components/Navbar";
import "@/app/globals.css";
import { Ubuntu } from "next/font/google";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: "400" });

export const metadata = {
	title: "My Store | buy here",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='container mx-auto'>
				<Navbar></Navbar>
				<main className='mx-20 h-screen flex justify-center align-center'>
					{children}
				</main>
			</body>
		</html>
	);
}
